# Generated by Django 6.1.1 on 2026-09-18 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО врача')),
                ('experience', models.PositiveIntegerField(verbose_name='Опыт (лет)')),
                ('specialization', models.CharField(choices=[('therapist', 'Стоматолог-терапевт'), ('surgeon', 'Стоматолог-хирург'), ('orthodontist', 'Ортодонт'), ('orthopedist', 'Ортопед'), ('implantologist', 'Имплантолог'), ('pediatric', 'Детский стоматолог')], max_length=50, verbose_name='Направление')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Стоимость приема')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время приема')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.doctor', verbose_name='Врач')),
            ],
        ),
    ]
